<a href="https://colab.research.google.com/github/chandrababu511/my-first-repo/blob/master/B2_Decision_Trees_Coding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import packages

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.tree import DecisionTreeClassifier, plot_tree, export_text
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import (accuracy_score, classification_report,
                             confusion_matrix, ConfusionMatrixDisplay)
from sklearn.preprocessing import StandardScaler

# Load the data

In [ ]:
df = sns.load_dataset('titanic')
df.head()

   survived  pclass     sex   age  ...  deck  embark_town  alive  alone
0         0       3    male  22.0  ...   NaN  Southampton     no  False
1         1       1  female  38.0  ...     C    Cherbourg    yes  False
2         1       3  female  26.0  ...   NaN  Southampton    yes   True
3         1       1  female  35.0  ...     C  Southampton    yes  False
4         0       3    male  35.0  ...   NaN  Southampton     no   True

[5 rows x 15 columns]

In [ ]:
df.shape

(891, 15)

In [ ]:
df['survived'].value_counts()

survived
0    549
1    342
Name: count, dtype: int64

In [ ]:
df['survived'].mean()

np.float64(0.3838383838383838)

In [ ]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [ ]:
# Let's use only couple of columns for the processing

features = ['pclass', 'sex', 'age', 'sibsp', 'parch', 'fare', 'embarked']
target = ['survived']

data = df[features + target].copy()
data

     pclass     sex   age  sibsp  parch     fare embarked  survived
0         3    male  22.0      1      0   7.2500        S         0
1         1  female  38.0      1      0  71.2833        C         1
2         3  female  26.0      0      0   7.9250        S         1
3         1  female  35.0      1      0  53.1000        S         1
4         3    male  35.0      0      0   8.0500        S         0
..      ...     ...   ...    ...    ...      ...      ...       ...
886       2    male  27.0      0      0  13.0000        S         0
887       1  female  19.0      0      0  30.0000        S         1
888       3  female   NaN      1      2  23.4500        S         0
889       1    male  26.0      0      0  30.0000        C         1
890       3    male  32.0      0      0   7.7500        Q         0

[891 rows x 8 columns]

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   pclass    891 non-null    int64
 1   sex       891 non-null    object
 2   age       714 non-null    float64
 3   sibsp     891 non-null    int64
 4   parch     891 non-null    int64
 5   fare      891 non-null    float64
 6   embarked  889 non-null    object
 7   survived  891 non-null    int64
dtypes: float64(2), int64(4), object(2)
memory usage: 55.8+ KB

In [ ]:
data['age'] = data['age'].fillna(data['age'].median())
data['embarked'] = data['embarked'].fillna(data['embarked'].mode()[0])
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   pclass    891 non-null    int64
 1   sex       891 non-null    object
 2   age       891 non-null    float64
 3   sibsp     891 non-null    int64
 4   parch     891 non-null    int64
 5   fare      891 non-null    float64
 6   embarked  891 non-null    object
 7   survived  891 non-null    int64
dtypes: float64(2), int64(4), object(2)
memory usage: 55.8+ KB

In [ ]:
data_encoded = pd.get_dummies(data, columns = ['sex', 'embarked'], drop_first= True)
data_encoded

     pclass   age  sibsp  parch  ...  survived  sex_male  embarked_Q  embarked_S
0         3  22.0      1      0  ...         0      True       False        True
1         1  38.0      1      0  ...         1     False       False       False
2         3  26.0      0      0  ...         1     False       False        True
3         1  35.0      1      0  ...         1     False       False        True
4         3  35.0      0      0  ...         0      True       False        True
..      ...   ...    ...    ...  ...       ...       ...         ...         ...
886       2  27.0      0      0  ...         0      True       False        True
887       1  19.0      0      0  ...         1     False       False        True
888       3  28.0      1      2  ...         0     False       False        True
889       1  26.0      0      0  ...         1      True       False       False
890       3  32.0      0      0  ...         0      True        True       False

[891 rows x 9 columns]

In [ ]:
data_encoded.shape

(891, 9)

In [ ]:
data_encoded.columns

Index(['pclass', 'age', 'sibsp', 'parch', 'fare', 'survived', 'sex_male',
       'embarked_Q', 'embarked_S'],
      dtype='object')

# Duplicates

In [ ]:
data_encoded = data_encoded.drop_duplicates()
print(data_encoded.shape)

(775, 9)

In [ ]:
data_encoded

     pclass   age  sibsp  parch  ...  survived  sex_male  embarked_Q  embarked_S
0         3  22.0      1      0  ...         0      True       False        True
1         1  38.0      1      0  ...         1     False       False       False
2         3  26.0      0      0  ...         1     False       False        True
3         1  35.0      1      0  ...         1     False       False        True
4         3  35.0      0      0  ...         0      True       False        True
..      ...   ...    ...    ...  ...       ...       ...         ...         ...
885       3  39.0      0      5  ...         0     False        True       False
887       1  19.0      0      0  ...         1     False       False        True
888       3  28.0      1      2  ...         0     False       False        True
889       1  26.0      0      0  ...         1      True       False       False
890       3  32.0      0      0  ...         0      True        True       False

[775 rows x 9 columns]

# Train Test Split

In [ ]:
target = 'survived'
X = data_encoded.drop(target, axis = 1)
y = data_encoded[target]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size = 0.2, random_state = 42, stratify = y
)
print(f"Training Set: {X_train.shape[0]} rows")
print(f"Test Set:     {X_test.shape[0]} rows")
print(f"\nTraining Survivial rate: {y_train.mean():.1%}")
print(f"Test Survivial rate:       {y_test.mean():.1%}")

Training Set: 620 rows
Test Set:     155 rows

Training Survivial rate: 41.3%
Test Survivial rate:       41.3%